"""initial_schema

Revision ID: 73e685e9111b
Revises: 
Create Date: 2026-09-28 20:56:17.660646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e685e9111b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('order_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('sender_info', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_sources_id'), 'order_sources', ['id'], unique=False)
    op.create_index(op.f('ix_order_sources_source_hash'), 'order_sources', ['source_hash'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'customer_code', name='uq_company_customer_code'),
    sa.UniqueConstraint('id', 'company_id', name='uq_customers_id_company_id')
    )
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('export_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('delimiter', sa.String(length=10), nullable=True),
    sa.Column('include_header', sa.Boolean(), nullable=False),
    sa.Column('encoding', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_profiles_company_id'), 'export_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_export_profiles_id'), 'export_profiles', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_company_product_sku'),
    sa.UniqueConstraint('id', 'company_id', name='uq_products_id_company_id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_description'), 'products', ['description'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('customer_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_contacts_customer_id'), 'customer_contacts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_contacts_id'), 'customer_contacts', ['id'], unique=False)
    op.create_table('customer_product_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('original_phrase', sa.String(length=255), nullable=False),
    sa.Column('normalized_phrase', sa.String(length=255), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.Column('corrected_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'normalized_phrase', name='uq_customer_normalized_alias')
    )
    op.create_index('ix_customer_alias_lookup', 'customer_product_aliases', ['customer_id', 'normalized_phrase'], unique=False)
    op.create_index(op.f('ix_customer_product_aliases_customer_id'), 'customer_product_aliases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_product_aliases_id'), 'customer_product_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_customer_product_aliases_product_id'), 'customer_product_aliases', ['product_id'], unique=False)
    op.create_table('export_field_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('export_profile_id', sa.Integer(), nullable=False),
    sa.Column('column_order', sa.Integer(), nullable=False),
    sa.Column('output_column_name', sa.String(length=100), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('source_field', sa.String(length=100), nullable=True),
    sa.Column('constant_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['export_profile_id'], ['export_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_field_mappings_export_profile_id'), 'export_field_mappings', ['export_profile_id'], unique=False)
    op.create_index(op.f('ix_export_field_mappings_id'), 'export_field_mappings', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_source_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('approved_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_export_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id', 'company_id'], ['customers.id', 'customers.company_id'], name='fk_order_customer_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_export_profile_id'], ['export_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_source_id'], ['order_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_company_idempotency_key'),
    sa.UniqueConstraint('company_id', 'order_number', name='uq_company_order_number')
    )
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_orders_order_source_id'), 'orders', ['order_source_id'], unique=False)
    op.create_table('packagings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('package_code', sa.String(length=100), nullable=True),
    sa.Column('packaging_barcode', sa.String(length=100), nullable=True),
    sa.Column('package_type', sa.String(length=100), nullable=False),
    sa.Column('pieces_per_case', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packagings_id'), 'packagings', ['id'], unique=False)
    op.create_index(op.f('ix_packagings_package_code'), 'packagings', ['package_code'], unique=False)
    op.create_index(op.f('ix_packagings_packaging_barcode'), 'packagings', ['packaging_barcode'], unique=False)
    op.create_index(op.f('ix_packagings_product_id'), 'packagings', ['product_id'], unique=False)
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('original_phrase', sa.String(length=255), nullable=False),
    sa.Column('normalized_phrase', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id', 'company_id'], ['products.id', 'products.company_id'], name='fk_product_alias_product_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_id', 'normalized_phrase', name='uq_company_product_global_alias')
    )
    op.create_index('ix_product_alias_lookup', 'product_aliases', ['company_id', 'normalized_phrase'], unique=False)
    op.create_index(op.f('ix_product_aliases_company_id'), 'product_aliases', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_aliases_id'), 'product_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_product_aliases_normalized_phrase'), 'product_aliases', ['normalized_phrase'], unique=False)
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    op.create_table('export_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('export_profile_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['export_profile_id'], ['export_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_export_profile_id'), 'export_records', ['export_profile_id'], unique=False)
    op.create_index(op.f('ix_export_records_id'), 'export_records', ['id'], unique=False)
    op.create_index(op.f('ix_export_records_order_id'), 'export_records', ['order_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(length=500), nullable=False),
    sa.Column('product_phrase', sa.String(length=500), nullable=False),
    sa.Column('requested_quantity', sa.Float(), nullable=False),
    sa.Column('requested_unit', sa.String(length=50), nullable=False),
    sa.Column('raw_unit', sa.String(length=50), nullable=True),
    sa.Column('unit_explicit', sa.Boolean(), nullable=False),
    sa.Column('matched_product_id', sa.Integer(), nullable=True),
    sa.Column('matched_packaging_id', sa.Integer(), nullable=True),
    sa.Column('final_sku', sa.String(length=100), nullable=True),
    sa.Column('final_quantity', sa.Float(), nullable=True),
    sa.Column('final_unit', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_reasons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['matched_packaging_id'], ['packagings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_id'), 'order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_order_lines_matched_product_id'), 'order_lines', ['matched_product_id'], unique=False)
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_table('human_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_line_id', sa.Integer(), nullable=True),
    sa.Column('original_phrase', sa.String(length=255), nullable=False),
    sa.Column('suggested_product_id', sa.Integer(), nullable=True),
    sa.Column('correct_product_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['correct_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_corrections_customer_id'), 'human_corrections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_human_corrections_id'), 'human_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_human_corrections_order_id'), 'human_corrections', ['order_id'], unique=False)
    op.create_index(op.f('ix_human_corrections_order_line_id'), 'human_corrections', ['order_line_id'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_candidates_id'), 'match_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_match_candidates_order_line_id'), 'match_candidates', ['order_line_id'], unique=False)
    op.create_index(op.f('ix_match_candidates_product_id'), 'match_candidates', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_candidates_product_id'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_order_line_id'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_human_corrections_order_line_id'), table_name='human_corrections')
    op.drop_index(op.f('ix_human_corrections_order_id'), table_name='human_corrections')
    op.drop_index(op.f('ix_human_corrections_id'), table_name='human_corrections')
    op.drop_index(op.f('ix_human_corrections_customer_id'), table_name='human_corrections')
    op.drop_table('human_corrections')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_matched_product_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_export_records_order_id'), table_name='export_records')
    op.drop_index(op.f('ix_export_records_id'), table_name='export_records')
    op.drop_index(op.f('ix_export_records_export_profile_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_normalized_phrase'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_company_id'), table_name='product_aliases')
    op.drop_index('ix_product_alias_lookup', table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_index(op.f('ix_packagings_product_id'), table_name='packagings')
    op.drop_index(op.f('ix_packagings_packaging_barcode'), table_name='packagings')
    op.drop_index(op.f('ix_packagings_package_code'), table_name='packagings')
    op.drop_index(op.f('ix_packagings_id'), table_name='packagings')
    op.drop_table('packagings')
    op.drop_index(op.f('ix_orders_order_source_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_export_field_mappings_id'), table_name='export_field_mappings')
    op.drop_index(op.f('ix_export_field_mappings_export_profile_id'), table_name='export_field_mappings')
    op.drop_table('export_field_mappings')
    op.drop_index(op.f('ix_customer_product_aliases_product_id'), table_name='customer_product_aliases')
    op.drop_index(op.f('ix_customer_product_aliases_id'), table_name='customer_product_aliases')
    op.drop_index(op.f('ix_customer_product_aliases_customer_id'), table_name='customer_product_aliases')
    op.drop_index('ix_customer_alias_lookup', table_name='customer_product_aliases')
    op.drop_table('customer_product_aliases')
    op.drop_index(op.f('ix_customer_contacts_id'), table_name='customer_contacts')
    op.drop_index(op.f('ix_customer_contacts_customer_id'), table_name='customer_contacts')
    op.drop_table('customer_contacts')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_description'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_export_profiles_id'), table_name='export_profiles')
    op.drop_index(op.f('ix_export_profiles_company_id'), table_name='export_profiles')
    op.drop_table('export_profiles')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_order_sources_source_hash'), table_name='order_sources')
    op.drop_index(op.f('ix_order_sources_id'), table_name='order_sources')
    op.drop_table('order_sources')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
